#!/bin/bash
# VizFlow Development Sprint Setup Guide

echo "🚀 VizFlow Sprint Development Guide"
echo "===================================="
echo ""

# Sprint 1 Setup
echo "📋 Sprint 1: Advanced Editor Setup"
echo "-----------------------------------"
echo "Install dependencies:"
echo "  npm install @monaco-editor/react pyodide"
echo ""
echo "Create files:"
echo "  src/components/Editor.jsx"
echo "  src/services/pythonRuntime.js"
echo "  src/hooks/useEditor.js"
echo ""
echo "Implementation checklist:"
echo "  ☐ Replace CodeEditor with Monaco Editor component"
echo "  ☐ Setup Pyodide runtime in pythonRuntime.js"
echo "  ☐ Add LSP support via language server"
echo "  ☐ Create useEditor hook for state management"
echo "  ☐ Test with sample PyTorch code"
echo ""

# Sprint 2 Setup
echo "📋 Sprint 2: Advanced Visualization Setup"
echo "-----------------------------------------"
echo "Install dependencies:"
echo "  npm install d3 html2canvas"
echo ""
echo "Create files:"
echo "  src/components/D3Visualization.jsx"
echo "  src/utils/frameworkDetector.js"
echo "  src/utils/export.js"
echo "  src/hooks/useVisualization.js"
echo ""
echo "Implementation checklist:"
echo "  ☐ Build D3 force-directed graph component"
echo "  ☐ Implement framework auto-detection"
echo "  ☐ Add PNG export via html2canvas"
echo "  ☐ Add SVG export functionality"
echo "  ☐ Build layer weight histogram"
echo "  ☐ Create zoom/pan controls"
echo ""

# Sprint 3 Setup
echo "📋 Sprint 3: Backend Integration Setup"
echo "-------------------------------------"
echo "Backend stack:"
echo "  FastAPI"
echo "  Uvicorn (ASGI server)"
echo "  WebSockets"
echo "  SQLite (local) or PostgreSQL (production)"
echo ""
echo "Frontend files to create:"
echo "  src/services/websocket.js"
echo "  src/services/api.js"
echo "  src/hooks/useBackend.js"
echo ""
echo "Backend files to create:"
echo "  backend/main.py"
echo "  backend/requirements.txt"
echo "  backend/services/parser.py"
echo "  backend/services/executor.py"
echo "  backend/database/models.py"
echo ""
echo "Implementation checklist:"
echo "  ☐ Setup FastAPI server"
echo "  ☐ Implement WebSocket endpoints"
echo "  ☐ Build model parsing service"
echo "  ☐ Create code execution service"
echo "  ☐ Implement authentication"
echo "  ☐ Setup database models"
echo "  ☐ Add project save/load functionality"
echo ""

# Development Commands
echo "📝 Development Commands"
echo "----------------------"
echo ""
echo "Start dev server:"
echo "  npm run dev"
echo ""
echo "Build for production:"
echo "  npm run build"
echo ""
echo "Run linting:"
echo "  npm run lint"
echo ""
echo "Preview production build:"
echo "  npm run preview"
echo ""

# Testing Tips
echo "🧪 Testing Tips"
echo "---------------"
echo ""
echo "Sprint 1 - Test models:"
echo "  • Simple: nn.Sequential(nn.Linear(10, 5))"
echo "  • Medium: VGG-style network"
echo "  • Complex: ResNet-50 clone"
echo ""
echo "Sprint 2 - Test exports:"
echo "  • PNG export quality"
echo "  • SVG scalability"
echo "  • Layer inspector accuracy"
echo ""
echo "Sprint 3 - Test backend:"
echo "  • WebSocket reconnection"
echo "  • Concurrent requests"
echo "  • Project sync"
echo ""

# Performance Optimization
echo "⚡ Performance Optimization Tips"
echo "--------------------------------"
echo ""
echo "• Lazy load Monaco Editor (split chunks)"
echo "• Memoize ModelVisualization component"
echo "• Debounce code editor changes"
echo "• Virtualize large model graphs with windowing"
echo "• Use Web Workers for parsing large models"
echo "• Cache framework detection results"
echo ""

# Useful Resources
echo "📚 Useful Resources"
echo "-------------------"
echo ""
echo "Monaco Editor:"
echo "  https://github.com/microsoft/monaco-editor"
echo ""
echo "D3.js Documentation:"
echo "  https://d3js.org/"
echo ""
echo "Pyodide (Python in Browser):"
echo "  https://pyodide.org/"
echo ""
echo "FastAPI:"
echo "  https://fastapi.tiangolo.com/"
echo ""
echo "WebSockets (MDN):"
echo "  https://developer.mozilla.org/en-US/docs/Web/API/WebSocket"
echo ""
